---
- name: check os compatibility
  fail:
    msg: 'Your OS {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported'
  when:
    - ansible_distribution != 'CentOS'
    - ansible_distribution_major_version|int != 7

- name: set python interpreter for centos 7
  set_fact:
    ansible_python_interpreter: /usr/bin/python
  when:
    - ansible_distribution_major_version|int == 7
